example:
- example/**
#
#pubspec:
#- pubspec.yaml
#
#github:
#- .github/**
#
#shelf:
#- lib/expansion_tile_group.dart
#
#types:
#- lib/src/types/*
#
#core:
#- lib/src/core/*
#
#test:
#- test/**
#
#document:
#- README.md