import 'package:expansion_tile_group/expansion_tile_group.dart';
import 'package:flutter/material.dart';

class ExpansionTileBorderItem extends ExpansionTileItem {
  ExpansionTileBorderItem({
    super.key,
    required super.title,
    required super.children,
    super.onExpansionChanged,
    super.expansionKey,
    super.initiallyExpanded,
    super.tilePadding,
    super.collapsedIconColor,
    super.expandedCrossAxisAlignment,
    super.iconColor,
    super.textColor,
    super.subtitle,
    super.maintainState = false,
    super.controlAffinity,
    super.collapsedTextColor,
    super.collapsedBackgroundColor,
    super.trailing,
    super.leading,
    super.backgroundColor,
    super.decoration,
    super.border,
    super.themeData,
    super.boxShadow,
    super.clipBehavior,
    super.collapsedBorderColor,
    super.expendedBorderColor,
    super.isHasTrailing,
    super.isEnableExpanded,
    super.isDefaultVerticalPadding,
    super.isHideSubtitleOnExpanded,
    super.trailingIcon,
    EdgeInsetsGeometry? childrenPadding,
    Alignment? expandedAlignment,
    BorderRadius? borderRadius,
  }) : super(
          borderRadius: borderRadius ?? BorderRadius.circular(8),
          childrenPadding: childrenPadding ??
              const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          expandedAlignment: expandedAlignment ?? Alignment.topLeft,
          isHasBottomBorder: true,
          isHasLeftBorder: true,
          isHasRightBorder: true,
          isHasTopBorder: true,
        );
}
